version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "CodeSwitch"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    env:
      # 避免用户环境里手动设置了旧版 GOROOT，导致标准库不匹配（iter / crypto/mlkem 等编译失败）
      GOROOT: ""
      GOTOOLCHAIN: auto
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    env:
      GOROOT: ""
      GOTOOLCHAIN: auto
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    env:
      GOROOT: ""
      GOTOOLCHAIN: auto
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    env:
      GOROOT: ""
      GOTOOLCHAIN: auto
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  package:dev:
    summary: Packages a debug build of the application
    env:
      GOROOT: ""
      GOTOOLCHAIN: auto
    cmds:
      - task: "{{OS}}:package:dev"
