// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RebuildStats 记录一次快照构建中远程数据的合并结果。
 */
export class RebuildStats {
    "totalModels": number;
    "remoteAdded": number;
    "remoteUpdated": number;

    /**
     * embedded 含扩展档位规则,远程基础价被忽略
     */
    "keptComplex": number;

    /**
     * normalized 与既有 canonical key 冲突被拒收
     */
    "droppedConflict": number;

    /** Creates a new RebuildStats instance. */
    constructor($$source: Partial<RebuildStats> = {}) {
        if (!("totalModels" in $$source)) {
            this["totalModels"] = 0;
        }
        if (!("remoteAdded" in $$source)) {
            this["remoteAdded"] = 0;
        }
        if (!("remoteUpdated" in $$source)) {
            this["remoteUpdated"] = 0;
        }
        if (!("keptComplex" in $$source)) {
            this["keptComplex"] = 0;
        }
        if (!("droppedConflict" in $$source)) {
            this["droppedConflict"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RebuildStats instance from a string or object.
     */
    static createFrom($$source: any = {}): RebuildStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RebuildStats($$parsedSource as Partial<RebuildStats>);
    }
}

/**
 * RemoteCatalog 单厂商目录。
 */
export class RemoteCatalog {
    "id": string;
    "models": { [_ in string]?: RemoteModel };

    /** Creates a new RemoteCatalog instance. */
    constructor($$source: Partial<RemoteCatalog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCatalog instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteCatalog {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new RemoteCatalog($$parsedSource as Partial<RemoteCatalog>);
    }
}

/**
 * RemoteCost 目录内价格,单位 USD/百万 token。
 */
export class RemoteCost {
    "input": number | null;
    "output": number | null;
    "cache_read": number | null;
    "cache_write": number | null;

    /** Creates a new RemoteCost instance. */
    constructor($$source: Partial<RemoteCost> = {}) {
        if (!("input" in $$source)) {
            this["input"] = null;
        }
        if (!("output" in $$source)) {
            this["output"] = null;
        }
        if (!("cache_read" in $$source)) {
            this["cache_read"] = null;
        }
        if (!("cache_write" in $$source)) {
            this["cache_write"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCost instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteCost {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteCost($$parsedSource as Partial<RemoteCost>);
    }
}

/**
 * RemoteLimit 上下文与输出窗口。
 */
export class RemoteLimit {
    "context": number;
    "output": number;

    /** Creates a new RemoteLimit instance. */
    constructor($$source: Partial<RemoteLimit> = {}) {
        if (!("context" in $$source)) {
            this["context"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteLimit instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteLimit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteLimit($$parsedSource as Partial<RemoteLimit>);
    }
}

/**
 * RemoteModalities 输入输出模态。
 */
export class RemoteModalities {
    "input": string[];
    "output": string[];

    /** Creates a new RemoteModalities instance. */
    constructor($$source: Partial<RemoteModalities> = {}) {
        if (!("input" in $$source)) {
            this["input"] = [];
        }
        if (!("output" in $$source)) {
            this["output"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteModalities instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteModalities {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField0_0($$parsedSource["input"]);
        }
        if ("output" in $$parsedSource) {
            $$parsedSource["output"] = $$createField1_0($$parsedSource["output"]);
        }
        return new RemoteModalities($$parsedSource as Partial<RemoteModalities>);
    }
}

/**
 * RemoteModel 目录内单个模型条目。
 */
export class RemoteModel {
    "id": string;
    "name": string;
    "family": string;
    "release_date": string;
    "last_updated": string;
    "reasoning": boolean;
    "tool_call": boolean | null;
    "cost": RemoteCost | null;
    "limit": RemoteLimit | null;
    "modalities": RemoteModalities | null;

    /** Creates a new RemoteModel instance. */
    constructor($$source: Partial<RemoteModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("family" in $$source)) {
            this["family"] = "";
        }
        if (!("release_date" in $$source)) {
            this["release_date"] = "";
        }
        if (!("last_updated" in $$source)) {
            this["last_updated"] = "";
        }
        if (!("reasoning" in $$source)) {
            this["reasoning"] = false;
        }
        if (!("tool_call" in $$source)) {
            this["tool_call"] = null;
        }
        if (!("cost" in $$source)) {
            this["cost"] = null;
        }
        if (!("limit" in $$source)) {
            this["limit"] = null;
        }
        if (!("modalities" in $$source)) {
            this["modalities"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteModel instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteModel {
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        const $$createField9_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cost" in $$parsedSource) {
            $$parsedSource["cost"] = $$createField7_0($$parsedSource["cost"]);
        }
        if ("limit" in $$parsedSource) {
            $$parsedSource["limit"] = $$createField8_0($$parsedSource["limit"]);
        }
        if ("modalities" in $$parsedSource) {
            $$parsedSource["modalities"] = $$createField9_0($$parsedSource["modalities"]);
        }
        return new RemoteModel($$parsedSource as Partial<RemoteModel>);
    }
}

// Private type creation functions
const $$createType0 = RemoteModel.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = RemoteCost.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = RemoteLimit.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = RemoteModalities.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
