// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * FocusMainWindow 聚焦主窗口（统一守卫入口，供前端 RPC 调用）
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3917281415);
}

export function OpenSecondWindow(): $CancellablePromise<void> {
    return $Call.ByID(1306260514);
}

export function SetTrayWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(3935785145, height);
}
