// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService 配置一键导出（issue #13）：把供应商/MCP/提示词/技能元数据
 * 打成单文件 JSON 包，包可被 ImportService 直接导回。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportWithDialog 弹系统保存对话框并导出。这是唯一暴露给前端的导出入口：
 * 接受路径参数的写文件方法一律不导出，避免 RPC 变成任意路径写入原语。
 * includeSecrets=false（默认脱敏）时清空所有已识别的凭据字段。
 */
export function ExportWithDialog(includeSecrets: boolean): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(1446804270, includeSecrets).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2391829448);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3255460908);
}

// Private type creation functions
const $$createType0 = $models.ExportResult.createFrom;
