// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CostSince(start: string, platform: string): $CancellablePromise<number> {
    return $Call.ByID(445919367, start, platform);
}

/**
 * GetRequestLogDetail 读取单条日志的出站请求详情（抓包模式录制的内容）
 */
export function GetRequestLogDetail(id: number): $CancellablePromise<$models.RequestLogDetail | null> {
    return $Call.ByID(1201574134, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HeatmapStats(days: number): $CancellablePromise<$models.HeatmapStat[]> {
    return $Call.ByID(1056815029, days).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListProviders(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(790916236, platform).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListRequestLogs(platform: string, provider: string, limit: number): $CancellablePromise<$models.ReqeustLog[]> {
    return $Call.ByID(1199056012, platform, provider, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ProviderDailyStats(platform: string): $CancellablePromise<$models.ProviderDailyStat[]> {
    return $Call.ByID(974013659, platform).then(($result: any) => {
        return $$createType8($result);
    });
}

export function StatsSince(platform: string): $CancellablePromise<$models.LogStats> {
    return $Call.ByID(2831143405, platform).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RequestLogDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.HeatmapStat.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.ReqeustLog.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.ProviderDailyStat.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.LogStats.createFrom;
