// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelSyncService 见文件头说明。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modelpricing$0 from "../resources/model-pricing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Catalogs 返回当前生效目录(浅拷贝;目录对象建成后不可变)。
 */
export function Catalogs(): $CancellablePromise<{ [_ in string]?: modelpricing$0.RemoteCatalog | null }> {
    return $Call.ByID(132814154).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetDefaultModels 返回各平台当前解析出的默认/探测模型。
 */
export function GetDefaultModels(): $CancellablePromise<$models.DefaultModels> {
    return $Call.ByID(3257098077).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSyncStatus 返回当前同步状态。
 */
export function GetSyncStatus(): $CancellablePromise<$models.ModelSyncStatus> {
    return $Call.ByID(3102243755).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RestoreBuiltinPricing 恢复内置数据:关闭自动同步(可再开启)、清空缓存与状态、
 * 立即以"嵌入 base + 内置种子"重建生效快照。
 */
export function RestoreBuiltinPricing(): $CancellablePromise<$models.ModelSyncStatus> {
    return $Call.ByID(664433879).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetApp 注入 Wails App 引用,用于向前端广播同步事件。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1084458757, app);
}

/**
 * Start 启动后台调度:延迟首查,此后每小时检查到期厂商。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2612134070);
}

/**
 * Stop 取消在途请求并等待后台退出(接入 app.OnShutdown)。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3154212062);
}

/**
 * SyncNow 手动全量同步(无视到期时间);已有批次在跑时返回当前状态不重入。
 */
export function SyncNow(): $CancellablePromise<$models.ModelSyncStatus> {
    return $Call.ByID(2251642215).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = modelpricing$0.RemoteCatalog.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $models.DefaultModels.createFrom;
const $$createType4 = $models.ModelSyncStatus.createFrom;
