// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PromptService 提示词管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeletePrompt 删除提示词
 */
export function DeletePrompt(platform: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(233228333, platform, id);
}

/**
 * EnablePrompt 启用指定提示词（会禁用其他所有提示词）
 */
export function EnablePrompt(platform: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(4030428505, platform, id);
}

/**
 * GetCurrentFileContent 获取当前提示词文件内容
 */
export function GetCurrentFileContent(platform: string): $CancellablePromise<string | null> {
    return $Call.ByID(3179736812, platform);
}

/**
 * GetPrompts 获取指定平台的所有提示词
 */
export function GetPrompts(platform: string): $CancellablePromise<{ [_ in string]?: $models.Prompt }> {
    return $Call.ByID(709954839, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromFile 从现有文件导入提示词
 */
export function ImportFromFile(platform: string): $CancellablePromise<string> {
    return $Call.ByID(3165650383, platform);
}

/**
 * ImportPrompts 批量导入提示词（batch 的键为平台 claude/codex/gemini）。
 * 按 ID 与名称（不区分大小写）查重，全部强制 Enabled=false 后一次性落盘，
 * 绝不改写 CLI 提示词文件。强制禁用的原因：标记 Enabled=true 但不写文件，
 * 首次 GetPrompts 会用磁盘上的旧内容覆盖导入正文；写文件则导入动作会
 * 静默覆盖用户当前 CLI 的全局提示词——两条路都不可接受。
 * 保存失败时回滚内存状态。返回实际新增数量。
 */
export function ImportPrompts(batch: { [_ in string]?: $models.Prompt[] }): $CancellablePromise<number> {
    return $Call.ByID(1587407428, batch);
}

/**
 * Start Wails生命周期方法
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3537442032);
}

/**
 * Stop Wails生命周期方法
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3274727284);
}

/**
 * StoredPrompts 返回已保存的提示词快照（只读，不触发外部文件同步）。
 * 供导入等后台流程查重使用：GetPrompts 的首次访问会把 CLI 提示词文件
 * 内容回填进 Enabled 项并落盘，状态检查不应产生这种写入副作用。
 */
export function StoredPrompts(platform: string): $CancellablePromise<{ [_ in string]?: $models.Prompt }> {
    return $Call.ByID(3989474382, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpsertPrompt 添加或更新提示词
 */
export function UpsertPrompt(platform: string, id: string, prompt: $models.Prompt): $CancellablePromise<void> {
    return $Call.ByID(1167812421, platform, id, prompt);
}

// Private type creation functions
const $$createType0 = $models.Prompt.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
