// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DuplicateProvider 复制供应商配置，生成新的副本
 * 返回新创建的 Provider 对象
 */
export function DuplicateProvider(kind: string, sourceID: number): $CancellablePromise<$models.Provider | null> {
    return $Call.ByID(1332089125, kind, sourceID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadProviders(kind: string): $CancellablePromise<$models.Provider[]> {
    return $Call.ByID(3413098935, kind).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LoadProvidersWithGen 返回配对一致的 (providers, 配置代数)。
 * 并发限流的容量热更新依赖两者配对。必须与写入方共用 ps.mu：
 * 写入方"改名文件→递增代数"两步之间存在窗口，锁外读取可能拿到
 * (新配置, 旧代数)，与在途旧副本同代后容量会被来回覆盖。
 * 锁内用 loadProvidersNoLock（其迁移保存不再加锁），无递归死锁。
 */
export function LoadProvidersWithGen(kind: string): $CancellablePromise<[$models.Provider[], number]> {
    return $Call.ByID(2303523163, kind).then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    });
}

/**
 * RenameProvider 改名 provider:事务更新 DB 中按 name 存储的历史数据,
 * 写入 48h alias 兜底 in-flight 请求,最后原子替换配置文件。
 * 
 * 校验规则:
 *   - newName 非空且 trim 后与 oldName 不等
 *   - 同 kind 下不存在其它 provider 用同名(当前 snapshot)
 *   - 48h 内 alias 表未占用该 newName
 *   - 该 provider_id 在 48h 内未 rename 过(禁止链式)
 */
export function RenameProvider(kind: string, id: number, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2498164164, kind, id, newName);
}

export function SaveProviders(kind: string, providers: $models.Provider[]): $CancellablePromise<void> {
    return $Call.ByID(1034860836, kind, providers);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(194327613);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(291391407);
}

// Private type creation functions
const $$createType0 = $models.Provider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
