// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Addr(): $CancellablePromise<string> {
    return $Call.ByID(285658449);
}

/**
 * BoundAddresses 返回本次启动实际绑定成功的监听地址。
 * 监听地址在启动时冻结，改了网络设置也要重启应用才生效，
 * 所以 UI 展示与"WSL 能不能连到"的判断都应以此为准。
 */
export function BoundAddresses(): $CancellablePromise<string[]> {
    return $Call.ByID(1450223930).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearCapturedRequests 清空全部抓包数据：所有会话 + 0 号旧数据的捕获内容
 * 分批清除（保留统计行本身），末批删除旧会话元数据；录制中则轮换出新会话。
 * 全局清除以代次推进兜在途行（任何旧代次行落库时自我置空）。
 * 磁盘空间不在此回收（逻辑清空）：VACUUM 移至设置页的显式维护操作，
 * 同步 VACUUM 曾把"清空"放大成分钟级排他锁全库冻结
 */
export function ClearCapturedRequests(): $CancellablePromise<number> {
    return $Call.ByID(3424084195);
}

/**
 * DeleteCaptureSession 删除单个会话：分批清除其捕获内容（保留统计行本身），
 * 末批删除会话元数据。删除活动会话时先在短事务内轮换出新会话（录制不中断、
 * 白纸重来）。墓碑兜住在途长流请求：采集发生在请求开始，落库时校验会话已删
 * 则自我置空；墓碑在元数据删除前就已生效，批处理期间无新行进入该会话
 */
export function DeleteCaptureSession(sessionID: number): $CancellablePromise<number> {
    return $Call.ByID(82781707, sessionID);
}

/**
 * ExportCaptureSessionWithDialog 弹系统保存对话框并导出指定会话的抓包内容。
 * opts 按数据类别裁剪导出字段（全 false 视为非法）。录制中的会话同样可导出。
 * 
 * 【安全告警】全量不脱敏：导出文件含明文 API Key、完整提示词与响应，切勿分享。
 * 单会话可达数百 MB，因此不整载内存：对话框确认后开只读事务逐行流式写入目标
 * 目录内的临时文件，成功后原子替换；未选中的大字段不进 SQL 投影
 */
export function ExportCaptureSessionWithDialog(sessionID: number, opts: $models.CaptureExportOptions): $CancellablePromise<$models.CaptureExportResult> {
    return $Call.ByID(587151650, sessionID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAllLastUsedProviders 获取所有平台最后使用的供应商
 * @author sm
 */
export function GetAllLastUsedProviders(): $CancellablePromise<{ [_ in string]?: $models.LastUsedProvider | null }> {
    return $Call.ByID(1820257126).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetCaptureSessionLogs 读取会话内的轻量请求行。
 * sinceID>0：增量模式，返回 id > sinceID 的新行（升序），供录制中的会话轮询追加；
 * 否则：初始/翻页模式，返回 id < beforeID（beforeID<=0 视为不设上界）的最新行（降序）。
 * limit 兜底 200、上限 500
 */
export function GetCaptureSessionLogs(sessionID: number, sinceID: number, beforeID: number, limit: number): $CancellablePromise<$models.CaptureSessionLogRow[]> {
    return $Call.ByID(3711165611, sessionID, sinceID, beforeID, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCaptureTotalBytes 返回全部抓包字段的存储字节总量（200MB 提醒用）。
 * "基线 + 增量"缓存：首次在 captureWriteMu 写锁内做一次全表 SUM 建基线
 * （与捕获 INSERT 线性化，某行不会既进 SUM 又进增量或两边都漏），此后
 * 写入侧在读锁内原子累加，维护操作完成后基线失效重建。
 * 取代旧实现"前端每 10s 一次全表扫描"——那是随库增长的无界周期开销
 */
export function GetCaptureTotalBytes(): $CancellablePromise<number> {
    return $Call.ByID(590634181);
}

/**
 * GetLastUsedProvider 获取指定平台最后使用的供应商
 * @author sm
 */
export function GetLastUsedProvider(platform: string): $CancellablePromise<$models.LastUsedProvider | null> {
    return $Call.ByID(4045318450, platform).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRequestCapture 读取抓包模式开关
 */
export function GetRequestCapture(): $CancellablePromise<boolean> {
    return $Call.ByID(1160443259);
}

/**
 * ListCaptureSessions 列出全部会话（新会话在前），含 0 号伪会话（仅当存在旧数据）
 */
export function ListCaptureSessions(): $CancellablePromise<$models.CaptureSessionInfo[]> {
    return $Call.ByID(2488871473).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetRequestCapture 设置抓包模式开关。录制开关为进程内状态、重启即关
 * （调试态功能，不持久化可避免用户遗忘后长期落盘敏感请求内容）；
 * 会话数据落库保留。开启即建会话，关闭即封会话。
 * 顺序约束：开启时先提交会话行再置位开关，否则竞态下捕获行会落到 0 号
 * 伪会话里；关闭时先摘开关再封会话
 */
export function SetRequestCapture(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2074094391, enabled);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1467206330);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3260822682);
}

/**
 * VacuumDatabase 显式回收数据库磁盘空间（设置页维护操作）。
 * 抓包清空/删除只做逻辑清除，被清内容仍占据主库 freelist；VACUUM 重写整库
 * 才能真正收缩文件。VACUUM 持排他锁可达分钟级，因此：
 *   - 前置要求录制已关闭，且经确认框明示"期间新请求的日志不会入库"；
 *   - 与清空/删除共用维护互斥（TryLock 拒绝并发）；
 *   - 全程置全局维护标志：普通落库与队列写入快速失败（fail-open），
 *     不去撞排他锁，转发链路与供应商并发配额不受牵连；
 *   - 用独立连接执行且 busy_timeout 收紧到 800ms：抢不到锁快速失败提示重试，
 *     不自旋 30 秒。
 */
export function VacuumDatabase(): $CancellablePromise<$models.VacuumResult> {
    return $Call.ByID(4163535544).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.CaptureExportResult.createFrom;
const $$createType2 = $models.LastUsedProvider.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $models.CaptureSessionLogRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.CaptureSessionInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.VacuumResult.createFrom;
