// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Addr(): $CancellablePromise<string> {
    return $Call.ByID(285658449);
}

/**
 * BoundAddresses 返回本次启动实际绑定成功的监听地址。
 * 监听地址在启动时冻结，改了网络设置也要重启应用才生效，
 * 所以 UI 展示与"WSL 能不能连到"的判断都应以此为准。
 */
export function BoundAddresses(): $CancellablePromise<string[]> {
    return $Call.ByID(1450223930).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearCapturedRequests 清空已捕获的请求详情（保留统计行本身）。
 * 同步直写（不走批量队列）：RPC 返回成功即代表已提交。返回清理行数
 */
export function ClearCapturedRequests(): $CancellablePromise<number> {
    return $Call.ByID(3424084195);
}

/**
 * GetAllLastUsedProviders 获取所有平台最后使用的供应商
 * @author sm
 */
export function GetAllLastUsedProviders(): $CancellablePromise<{ [_ in string]?: $models.LastUsedProvider | null }> {
    return $Call.ByID(1820257126).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLastUsedProvider 获取指定平台最后使用的供应商
 * @author sm
 */
export function GetLastUsedProvider(platform: string): $CancellablePromise<$models.LastUsedProvider | null> {
    return $Call.ByID(4045318450, platform).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRequestCapture 读取抓包模式开关
 */
export function GetRequestCapture(): $CancellablePromise<boolean> {
    return $Call.ByID(1160443259);
}

/**
 * SetRequestCapture 设置抓包模式开关。进程内状态、重启即关：
 * 这是调试态功能，不持久化可避免用户遗忘后长期落盘敏感请求内容
 */
export function SetRequestCapture(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2074094391, enabled);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1467206330);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3260822682);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.LastUsedProvider.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
